
# Configuration du bucket de stockage pour les images
[[storage.buckets]]
name = "images"
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/webp", "image/gif"]
