
project_id = "vbjitiitrxbiyznrfvyx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
uri = "http://localhost:54321"

[realtime]
enabled = true

[functions]

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
