// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbjitiitrxbiyznrfvyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiaml0aWl0cnhiaXl6bnJmdnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODM4NDQsImV4cCI6MjA1OTM1OTg0NH0.otVow8F39Bj9_WihFX729_gVA9oAWzRd37xRd7eTHEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);